import type { Product } from '../types/Product';

export const products: Product[] = [
  {
    id: 1,
    title: 'Carregador USB Lightning 40W',
    description: 'Carregador USB Lightning 40W para iPhone e iPad',
    image: '/images/products/produto1.jpg',
    badges: ['Novo', 'Popular'],
    price: 44.99,
    originalPrice: 59.99,
    rating: 4.7,
    reviewCount: 124,
    category: 'acessorio',
    isFavorite: false,
    isOnChart: false,
  },
  {
    id: 2,
    title: 'Carregador USB-C 40W',
    description: 'Carregador USB-C para celulares e tablets',
    image: '/images/products/produto2.jpg',
    badges: ['Oferta'],
    price: 49.99,
    originalPrice: 69.99,
    rating: 4.4,
    reviewCount: 88,
    category: 'acessorio',
    isFavorite: false,
    isOnChart: false,
  },
  {
    id: 3,
    title: 'Carregador por Indução 15W',
    description: 'Carregador por indução 15W para celulares',
    image: '/images/products/produto2.jpg',
    badges: ['Destaque', 'Edição Limitada'],
    price: 59.99,
    originalPrice: 79.99,
    rating: 4.8,
    reviewCount: 212,
    category: 'acessorio',
    isFavorite: false,
    isOnChart: false,
  },
  {
    id: 4,
    title: 'Fone Bluetooth Pro X',
    description: 'Fones de ouvido sem fio com cancelamento de ruído',
    image: '/images/products/produto1.jpg',
    badges: ['Popular'],
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.6,
    reviewCount: 321,
    category: 'acessorio',
    isFavorite: false,
    isOnChart: false,
  },
  {
    id: 5,
    title: 'Cabo USB-C para Lightning 2m',
    description: 'Cabo de 2 metros compatível com iPhone e iPad',
    image: '/images/products/produto2.jpg',
    badges: ['Novo'],
    price: 29.99,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 54,
    category: 'acessorio',
    isFavorite: false,
    isOnChart: false,
  },
  {
    id: 6,
    title: 'Adaptador HDMI para USB-C',
    description: 'Adaptador de vídeo 4K para conectar em monitores e TVs',
    image: '/images/products/produto1.jpg',
    badges: ['Oferta', 'Destaque'],
    price: 39.99,
    originalPrice: 49.99,
    rating: 4.1,
    reviewCount: 77,
    category: 'acessorio',
    isFavorite: false,
    isOnChart: false,
  },
];
