import type { Product } from '../types/Product';

export const products: Product[] = [
  {
    id: 1,
    title: 'Carregador USB Lightning 40W',
    description:
      'Carregamento rápido e seguro para dispositivos Apple com potência de 40W. Ideal para uso doméstico ou viagens.',
    image: '/images/products/produto1.jpg',
    badges: ['Novo', 'Popular'],
    price: 44.99,
    originalPrice: 59.99,
    rating: 4.8,
    reviewCount: 3,
    category: 'accessories',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 2,
    title: 'Adaptador USB-C 20W',
    description:
      'Compacto e eficiente, fornece carregamento rápido via USB-C. Compatível com smartphones, tablets e mais.',
    image: '/images/products/produto2.jpg',
    badges: ['Essencial', 'Novo'],
    price: 44.99,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 5,
    category: 'accessories',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 3,
    title: 'Carregador Megsafe Indução Portátil',
    description: 'Design magnético moderno com carregamento sem fio rápido. Perfeito para iPhones com MagSafe.',
    image: '/images/products/produto3.webp',
    badges: ['Destaque', 'Sem Fio'],
    price: 39.99,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 4,
    category: 'accessories',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 4,
    title: 'Fone Bluetooth Pro X',
    description:
      'Áudio de alta fidelidade com cancelamento de ruído ativo. Bateria de longa duração e conforto prolongado.',
    image: '/images/products/produto4.jpg',
    badges: ['Premium', 'Destaque'],
    price: 89.99,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 13,
    category: 'accessories',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 5,
    title: 'HUB 4 em 1 USB-C HDMI Ethernet',
    description: 'Expanda a conectividade do seu notebook com HDMI, Ethernet e mais. Ideal para trabalho e estudos.',
    image: '/images/products/produto5.webp',
    badges: ['Multiuso', 'Essencial'],
    price: 74.99,
    originalPrice: null,
    rating: 4.3,
    reviewCount: 22,
    category: 'accessories',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 6,
    title: 'Adaptador USB C para HDMI',
    description: 'Transmita vídeos em alta resolução do seu dispositivo USB-C para TVs e monitores via HDMI.',
    image: '/images/products/produto6.jpeg',
    badges: ['Prático', 'Destaque'],
    price: 29.99,
    originalPrice: 49.99,
    rating: 4.1,
    reviewCount: 7,
    category: 'accessories',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 7,
    title: 'Placa de vídeo Dual Geforce RTX 30 Series',
    description: 'Performance de alto nível para jogos AAA e criação de conteúdo com Ray Tracing e DLSS.',
    image: '/images/products/produto7.jpeg',
    badges: ['Gamer', 'Alta Performance'],
    price: 1299.99,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 9,
    category: 'components',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 8,
    title: 'Placa de vídeo RX 7000 Series',
    description: 'Gráficos imersivos e eficiência de energia com arquitetura RDNA 3. Ideal para gamers exigentes.',
    image: '/images/products/produto8.jpeg',
    badges: ['Lançamento', 'Destaque'],
    price: 1899.99,
    originalPrice: 2099.99,
    rating: 4.37,
    reviewCount: 12,
    category: 'components',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 9,
    title: 'Processador Ryzen 7 5000 Series 3.8GHz',
    description: '8 núcleos de desempenho extremo para multitarefas, jogos e criação de conteúdo.',
    image: '/images/products/produto9.jpeg',
    badges: ['Desempenho'],
    price: 599.99,
    originalPrice: null,
    rating: 3.9,
    reviewCount: 4,
    category: 'components',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 10,
    title: 'Processador Core i3 5ª Geração 3.2GHz',
    description: 'Ideal para tarefas do dia a dia, com equilíbrio entre eficiência e custo-benefício.',
    image: '/images/products/produto10.webp',
    badges: ['Econômico', 'Confiável'],
    price: 689.99,
    originalPrice: 899.99,
    rating: 4.2,
    reviewCount: 7,
    category: 'components',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 11,
    title: 'Gabinete Gamer 4 Fans RGB 500W',
    description: 'Estilo e ventilação garantidos com 4 coolers RGB e fonte integrada de 500W.',
    image: '/images/products/produto11.webp',
    badges: ['RGB', 'Gamer'],
    price: 89.99,
    originalPrice: null,
    rating: 3.8,
    reviewCount: 14,
    category: 'components',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 12,
    title: 'Placa Mãe H410M Ddr4',
    description: 'Compatível com processadores Intel de 10ª geração, oferece estabilidade e ótimo custo-benefício.',
    image: '/images/products/produto12.webp',
    badges: ['Compatível', 'Destaque'],
    price: 449.99,
    originalPrice: 549.99,
    rating: 4.1,
    reviewCount: 11,
    category: 'components',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 13,
    title: 'Controle Dualshock AnalógicoCom Fio Pc Gamer',
    description: 'Precisão e resposta rápida com design ergonômico. Ideal para jogos no PC.',
    image: '/images/products/produto13.jpeg',
    badges: ['Clássico', 'Plug & Play'],
    price: 59.99,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 10,
    category: 'gamer',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 14,
    title: 'Controle Gamer Sem Fio Para Celular',
    description: 'Conecte via Bluetooth e jogue com conforto onde quiser. Compatível com Android e iOS.',
    image: '/images/products/produto14.webp',
    badges: ['Mobile'],
    price: 29.99,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 6,
    category: 'gamer',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 15,
    title: 'Cadeira Gamer Preto e Vermelho',
    description: 'Conforto e estilo para longas sessões de jogo ou trabalho com suporte lombar ajustável.',
    image: '/images/products/produto15.webp',
    badges: ['Ergonômica', 'Destaque'],
    price: 499.99,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 22,
    category: 'gamer',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 16,
    title: 'Suporte para Headset',
    description: 'Organização prática com design moderno. Ideal para manter sua estação gamer arrumada.',
    image: '/images/products/produto16.jpg',
    badges: ['Organização', 'Minimalista'],
    price: 49.99,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 14,
    category: 'gamer',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 17,
    title: 'Placa de Captura 4K Pro',
    description: 'Grave e transmita com qualidade profissional em até 4K. Ideal para streamers e criadores.',
    image: '/images/products/produto17.webp',
    badges: ['Profissional', 'Destaque'],
    price: 2599.99,
    originalPrice: 2999.99,
    rating: 4.1,
    reviewCount: 8,
    category: 'gamer',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 18,
    title: 'Notebook Vision C14 Lumina Bar Celeron',
    description: 'Equipado com Intel Celeron e tela HD. Ideal para navegação e tarefas básicas.',
    image: '/images/products/produto18.jpg',
    badges: ['Popular', 'Econômico'],
    price: 1499.99,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 16,
    category: 'notebooks',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 19,
    title: 'Notebook ULTRA Intel i5 10ª Geração Touchscreen',
    description: 'Potente e versátil com tela sensível ao toque. Ideal para produtividade e mobilidade.',
    image: '/images/products/produto19.webp',
    badges: ['Oferta', 'Portátil'],
    price: 2599.99,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 18,
    category: 'notebooks',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 20,
    title: 'Macbook Air M1 8GB 256GB SSD',
    description: 'Desempenho e eficiência com chip Apple M1. Leve, silencioso e poderoso.',
    image: '/images/products/produto20.jpeg',
    badges: ['Premium'],
    price: 4999.999,
    originalPrice: null,
    rating: 4.4,
    reviewCount: 13,
    category: 'notebooks',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 21,
    title: 'Macbook Pro 13.6 Apple M2 Chip Ssd Starlight',
    description: 'Potência profissional com o novo chip M2 e design premium em Starlight.',
    image: '/images/products/produto21.jpeg',
    badges: ['Destaque', 'Premium'],
    price: 7999.99,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 8,
    category: 'notebooks',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 22,
    title: 'Galaxy Book4 360 Ssd 15.6 Polegadas FullHD',
    description: 'Notebook conversível com tela Full HD e SSD rápido. Perfeito para produtividade e entretenimento.',
    image: '/images/products/produto22.jpg',
    badges: ['2 em 1', 'Mais Vendidos'],
    price: 2999.99,
    originalPrice: 3499.99,
    rating: 4.8,
    reviewCount: 10,
    category: 'notebooks',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 23,
    title: 'Fone Gamer Microfone Articulado Rgb',
    description: 'Som potente, microfone flexível e visual RGB. Ideal para jogos online.',
    image: '/images/products/produto23.webp',
    badges: ['Essencial', 'Destaque'],
    price: 399.99,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 11,
    category: 'peripherals',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 24,
    title: 'Mouse Gamer 6 Macros 8500 DPI',
    description: 'Alta precisão, personalização de macros e design ergonômico para performance nos jogos.',
    image: '/images/products/produto24.jpg',
    badges: ['Oferta', 'Mais Vendidos'],
    price: 199.99,
    originalPrice: null,
    rating: 4.1,
    reviewCount: 5,
    category: 'peripherals',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 25,
    title: 'Mousepad Logitech RGB 320x275mm',
    description: 'Superfície otimizada com iluminação RGB. Perfeito para jogadores exigentes.',
    image: '/images/products/produto25.webp',
    badges: ['Popular', 'Mais Vendidos'],
    price: 89.99,
    originalPrice: null,
    rating: 4.6,
    reviewCount: 11,
    category: 'peripherals',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 26,
    title: 'Teclado e Mouse Sem Fio, Bateria',
    description: 'Conjunto compacto e eficiente com longa duração de bateria. Ideal para uso diário.',
    image: '/images/products/produto26.jpg',
    badges: ['Sem fio', 'Durabilidade'],
    price: 399.99,
    originalPrice: 499.99,
    rating: 4.1,
    reviewCount: 15,
    category: 'peripherals',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 27,
    title: 'Monitor Samsung 28 Polegadas UHD 4K HDMI',
    description: 'Imagem nítida com resolução 4K e conexão HDMI. Excelente para criação e entretenimento.',
    image: '/images/products/produto27.jpg',
    badges: ['Premium'],
    price: 799.99,
    originalPrice: null,
    rating: 3.9,
    reviewCount: 24,

    category: 'peripherals',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 28,
    title: 'Celular Galaxy S24 ULTRA 5G 512GB 12GB RAM',
    description: 'Tecnologia de ponta com câmera avançada, 5G e alto desempenho.',
    image: '/images/products/produto28.webp',
    badges: ['Econômico', 'Popular'],
    price: 1299.99,
    originalPrice: null,
    rating: 4.0,
    reviewCount: 31,
    category: 'smartphones',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 29,
    title: 'Celular POCO C65 8GB+256GB',
    description: 'Desempenho rápido e ótimo armazenamento. Um dos melhores custo-benefício do mercado.',
    image: '/images/products/produto29.jpg',
    badges: ['Oferta', 'Destaque'],
    price: 1899.99,
    originalPrice: null,
    rating: 4.2,
    reviewCount: 20,
    category: 'smartphones',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 30,
    title: 'Celular iPhone 13 Pro Max 128GB',
    description: 'Tela Super Retina, câmeras avançadas e desempenho excepcional.',
    image: '/images/products/produto30.webp',
    badges: ['Profissional', 'Destaque'],
    price: 2099.99,
    originalPrice: 2899.99,
    rating: 4.4,
    reviewCount: 44,
    category: 'smartphones',
    isFavorite: false,
    isOnCart: false,
  },
  {
    id: 31,
    title: 'iPhone SE 64GB Red',
    description: 'Compacto, poderoso e acessível. A escolha ideal para quem ama iOS.',
    image: '/images/products/produto31.webp',
    badges: ['Oferta', 'Essencial'],
    price: 1499.99,
    originalPrice: 1899.99,
    rating: 3.9,
    reviewCount: 45,
    category: 'smartphones',
    isFavorite: false,
    isOnCart: false,
  },
];
